Content:
  - ${ROOT_DIR}/doc/content
  - ${MOOSE_DIR}/framework/doc/content
  - ${MOOSE_DIR}/modules/heat_conduction/doc/content
  - ${MOOSE_DIR}/modules/ray_tracing/doc/content
  - ${MOOSE_DIR}/modules/tensor_mechanics/doc/content
  - ${MOOSE_DIR}/modules/phase_field/doc/content
Renderer:
  type:                            MooseDocs.base.MaterializeRenderer
  favicon:                         media/raccoon_icon.png
Extensions:
  MooseDocs.extensions.navigation:
    name:                          "RACCOON"
    repo:                          https://github.com/hugary1995/raccoon
    home:                          https://hugary1995.github.io/raccoon/index.html
    menu:
      Install:                     install/index.md
      Theory:                      theory/index.md
      Modules:                     modules/index.md
      Syntax:                      syntax/index.md
      Contribute:                  contribute/index.md
  MooseDocs.extensions.bibtex:
    duplicates:
      - kim_phase-field_1999 # referenced in both Tensor Mechanics and Phase Field
      - hales15homogenization # referenced in both Tensor Mechanics and Heat Conduction
  MooseDocs.extensions.katex:
    macros:
      \bs:                         "\\boldsymbol{#1}"
      \normal:                     "\\bs{n}"
      \divergence:                 "\\nabla \\cdot"
      \norm:                       "\\left\\lVert#1\\right\\rVert"
      \diff:                       "\\text{ d}#1"
      \total:                      "\\text{total}"
      \internal:                   "\\text{internal}"
      \external:                   "\\text{external}"
      \elastic:                    "\\text{elastic}"
      \fracture:                   "\\text{fracture}"
      \critical:                   "\\text{critical}"
      \activeenergy:               "{\\left< A \\right>}"
      \inactiveenergy:             "{\\left< I \\right>}"
      \Gc:                         "{\\mathcal{G}_c}"
      \strain:                     "\\bs{\\varepsilon}"
      \stress:                     "\\bs{\\sigma}"
      \xstress:                    "\\widetilde{\\stress}"
      \macaulay:                   "\\left<#1\\right>"
      \body:                       "\\Omega"
      \bodyboundary:               "{\\partial\\body}"
      \grad:                       "\\bs{\\nabla}"
  MooseDocs.extensions.appsyntax:
    executable:                    ${ROOT_DIR}
    remove:
      framework:                   !include ${MOOSE_DIR}/framework/doc/remove.yml
  MooseDocs.extensions.common:
    shortcuts:                     !include ${MOOSE_DIR}/framework/doc/globals.yml
  MooseDocs.extensions.acronym:
    acronyms:                      !include ${MOOSE_DIR}/framework/doc/acronyms.yml
  MooseDocs.extensions.template:
    active:                        True
  MooseDocs.extensions.sqa:
      active:                      False
